#!/bin/sh /etc/rc.common
# Copyright (C) 2007 OpenWrt.org

START=99
USE_PROCD=1

PROG="/usr/bin/arm"

start_service() {
			  chmod a+x ${PROG}
        procd_open_instance
        procd_set_param command ${PROG}
        procd_set_param respawn 3600 5 0
        procd_close_instance
}

